Package Requirements

In [1]:
!pip install ddgs
!pip install httpx
!pip install newspaper3k
!pip install lxml_html_clean

Requirement already satisfied: ddgs in c:\users\faman\appdata\roaming\python\python313\site-packages (9.10.0)
Requirement already satisfied: click>=8.1.8 in c:\users\faman\.conda\envs\qc\lib\site-packages (from ddgs) (8.3.1)
Requirement already satisfied: primp>=0.15.0 in c:\users\faman\appdata\roaming\python\python313\site-packages (from ddgs) (1.0.0)
Requirement already satisfied: lxml>=4.9.4 in c:\users\faman\.conda\envs\qc\lib\site-packages (from ddgs) (6.0.2)
Requirement already satisfied: httpx>=0.28.1 in c:\users\faman\.conda\envs\qc\lib\site-packages (from httpx[brotli,http2,socks]>=0.28.1->ddgs) (0.28.1)
Requirement already satisfied: fake-useragent>=2.2.0 in c:\users\faman\appdata\roaming\python\python313\site-packages (from ddgs) (2.2.0)
Requirement already satisfied: colorama in c:\users\faman\.conda\envs\qc\lib\site-packages (from click>=8.1.8->ddgs) (0.4.6)
Requirement already satisfied: anyio in c:\users\faman\.conda\envs\qc\lib\site-packages (from httpx>=0.28.1->httpx[brotli,http2,socks]>=0.28.1->ddgs) (4.12.1)
Requirement already satisfied: certifi in c:\users\faman\.conda\envs\qc\lib\site-packages (from httpx>=0.28.1->httpx[brotli,http2,socks]>=0.28.1->ddgs) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\users\faman\.conda\envs\qc\lib\site-packages (from httpx>=0.28.1->httpx[brotli,http2,socks]>=0.28.1->ddgs) (1.0.9)
Requirement already satisfied: idna in c:\users\faman\.conda\envs\qc\lib\site-packages (from httpx>=0.28.1->httpx[brotli,http2,socks]>=0.28.1->ddgs) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\faman\.conda\envs\qc\lib\site-packages (from httpcore==1.*->httpx>=0.28.1->httpx[brotli,http2,socks]>=0.28.1->ddgs) (0.16.0)
Requirement already satisfied: brotli in c:\users\faman\appdata\roaming\python\python313\site-packages (from httpx[brotli,http2,socks]>=0.28.1->ddgs) (1.2.0)
Requirement already satisfied: h2<5,>=3 in c:\users\faman\appdata\roaming\python\python313\site-packages (from httpx[brotli,http2,socks]>=0.28.1->ddgs) (4.3.0)
Requirement already satisfied: socksio==1.* in c:\users\faman\appdata\roaming\python\python313\site-packages (from httpx[brotli,http2,socks]>=0.28.1->ddgs) (1.0.0)
Requirement already satisfied: hyperframe<7,>=6.1 in c:\users\faman\appdata\roaming\python\python313\site-packages (from h2<5,>=3->httpx[brotli,http2,socks]>=0.28.1->ddgs) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in c:\users\faman\appdata\roaming\python\python313\site-packages (from h2<5,>=3->httpx[brotli,http2,socks]>=0.28.1->ddgs) (4.1.0)
Requirement already satisfied: httpx in c:\users\faman\.conda\envs\qc\lib\site-packages (0.28.1)
Requirement already satisfied: anyio in c:\users\faman\.conda\envs\qc\lib\site-packages (from httpx) (4.12.1)
Requirement already satisfied: certifi in c:\users\faman\.conda\envs\qc\lib\site-packages (from httpx) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\users\faman\.conda\envs\qc\lib\site-packages (from httpx) (1.0.9)
Requirement already satisfied: idna in c:\users\faman\.conda\envs\qc\lib\site-packages (from httpx) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\faman\.conda\envs\qc\lib\site-packages (from httpcore==1.*->httpx) (0.16.0)
Requirement already satisfied: newspaper3k in c:\users\faman\appdata\roaming\python\python313\site-packages (0.2.8)
Requirement already satisfied: beautifulsoup4>=4.4.1 in c:\users\faman\.conda\envs\qc\lib\site-packages (from newspaper3k) (4.14.3)
Requirement already satisfied: Pillow>=3.3.0 in c:\users\faman\.conda\envs\qc\lib\site-packages (from newspaper3k) (12.0.0)
Requirement already satisfied: PyYAML>=3.11 in c:\users\faman\.conda\envs\qc\lib\site-packages (from newspaper3k) (6.0.3)
Requirement already satisfied: cssselect>=0.9.2 in c:\users\faman\.conda\envs\qc\lib\site-packages (from newspaper3k) (1.4.0)
Requirement already satisfied: lxml>=3.6.0 in c:\users\faman\.conda\envs\qc\lib\site-packages (from newspaper3k) (6.0.2)
Requirement already satisfied: nltk>=3.2.1 in c:\users\faman\.conda\envs\qc\lib\site-packages (from newspaper3k) (3.9.2)
Requirement already satisfied: requests>=2.10.0 in c:\users\faman\.conda\envs\qc\lib\site-packages (from newspaper3k) (2.32.5)
Requirement already satisfied: feedparser>=5.2.1 in c:\users\faman\appdata\roaming\python\python313\site-packages (from newspaper3k) (6.0.12)
Requirement already satisfied: tldextract>=2.0.1 in c:\users\faman\.conda\envs\qc\lib\site-packages (from newspaper3k) (5.3.1)
Requirement already satisfied: feedfinder2>=0.0.4 in c:\users\faman\appdata\roaming\python\python313\site-packages (from newspaper3k) (0.0.4)
Requirement already satisfied: jieba3k>=0.35.1 in c:\users\faman\appdata\roaming\python\python313\site-packages (from newspaper3k) (0.35.1)
Requirement already satisfied: python-dateutil>=2.5.3 in c:\users\faman\.conda\envs\qc\lib\site-packages (from newspaper3k) (2.9.0.post0)
Requirement already satisfied: tinysegmenter==0.3 in c:\users\faman\appdata\roaming\python\python313\site-packages (from newspaper3k) (0.3)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\faman\.conda\envs\qc\lib\site-packages (from beautifulsoup4>=4.4.1->newspaper3k) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\faman\.conda\envs\qc\lib\site-packages (from beautifulsoup4>=4.4.1->newspaper3k) (4.15.0)
Requirement already satisfied: six in c:\users\faman\.conda\envs\qc\lib\site-packages (from feedfinder2>=0.0.4->newspaper3k) (1.17.0)
Requirement already satisfied: sgmllib3k in c:\users\faman\appdata\roaming\python\python313\site-packages (from feedparser>=5.2.1->newspaper3k) (1.0.0)
Requirement already satisfied: click in c:\users\faman\.conda\envs\qc\lib\site-packages (from nltk>=3.2.1->newspaper3k) (8.3.1)
Requirement already satisfied: joblib in c:\users\faman\.conda\envs\qc\lib\site-packages (from nltk>=3.2.1->newspaper3k) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\faman\.conda\envs\qc\lib\site-packages (from nltk>=3.2.1->newspaper3k) (2025.11.3)
Requirement already satisfied: tqdm in c:\users\faman\.conda\envs\qc\lib\site-packages (from nltk>=3.2.1->newspaper3k) (4.67.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\faman\.conda\envs\qc\lib\site-packages (from requests>=2.10.0->newspaper3k) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\faman\.conda\envs\qc\lib\site-packages (from requests>=2.10.0->newspaper3k) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\faman\.conda\envs\qc\lib\site-packages (from requests>=2.10.0->newspaper3k) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\faman\.conda\envs\qc\lib\site-packages (from requests>=2.10.0->newspaper3k) (2025.11.12)
Requirement already satisfied: requests-file>=1.4 in c:\users\faman\.conda\envs\qc\lib\site-packages (from tldextract>=2.0.1->newspaper3k) (3.0.1)
Requirement already satisfied: filelock>=3.0.8 in c:\users\faman\.conda\envs\qc\lib\site-packages (from tldextract>=2.0.1->newspaper3k) (3.24.3)
Requirement already satisfied: colorama in c:\users\faman\.conda\envs\qc\lib\site-packages (from click->nltk>=3.2.1->newspaper3k) (0.4.6)
Requirement already satisfied: lxml_html_clean in c:\users\faman\appdata\roaming\python\python313\site-packages (0.4.3)
Requirement already satisfied: lxml in c:\users\faman\.conda\envs\qc\lib\site-packages (from lxml_html_clean) (6.0.2)

Retrieve articles using duckduckgo search text method - no filter applied yet

In [2]:
import pandas as pd
from ddgs import DDGS
import newspaper
from newspaper import Article

In [12]:
results = DDGS().text(query="galgotias impact ai summit", region="in-en",safesearch= "off", timelimit="7d", max_results=30)
df=pd.DataFrame(results)
df

,title,href,body
0,Galgotias University booted from India AI Impa...,https://apnews.com/article/india-ai-chinese-ga...,A private Indian university has been booted fr...
1,"Made in China, unmade at summit: Galgotias exi...",https://indianexpress.com/article/india/galgot...,Greater Noida-based Galgotias University was m...
2,Galgotias University asked to vacate AI Impact...,https://economictimes.indiatimes.com/ai/ai-ins...,Galgotias University faced removal from the AI...
3,Galgotias University staff leave AI Impact Exp...,https://www.cnbctv18.com/technology/galgotias-...,Galgotias University confirms its Robodog at A...
4,"Exit, blame, warning: Galgotias' Chinese robod...",https://www.hindustantimes.com/india-news/exit...,Galgotias University found itself in the eye o...
5,Galgotias University AI Robot Dog Controversy ...,https://www.ndtv.com/india-news/galgotias-univ...,A row has erupted at the India AI Impact Summi...
6,Galgotias University officials leave AI Impact...,https://www.livemint.com/news/india/galgotias-...,This came after reports suggested that Galgoti...
7,Galgotias University asked to vacate AI Summit...,https://www.thehindu.com/sci-tech/technology/g...,Organisers of the AI Impact Summit ousted priv...
8,Galgotias University Expelled From India AI Su...,https://www.outlookbusiness.com/news/galgotias...,Galgotias University Expelled From India AI Su...
9,Galgotias University vacate stall at India AI ...,https://www.wionews.com/world/-it-is-a-legacy-...,Galgotias University staff and officials vacat...

In [13]:
for url in df['href']:
    try:
        article = Article(url)
        article.download()
        article.parse()
        df.loc[df['href'] == url, 'text'] = article.text
    except Exception as e:
        print(f"Error processing URL {url}: {e}")
df

Error processing URL https://www.hindustantimes.com/india-news/exit-blame-apology-and-centres-warning-galgotias-universitys-chinese-robodog-row-at-ai-summit-2026-key-points-101771466897249.html: Article `download()` failed with 403 Client Error: Forbidden for url: https://www.hindustantimes.com/india-news/exit-blame-apology-and-centres-warning-galgotias-universitys-chinese-robodog-row-at-ai-summit-2026-key-points-101771466897249.html on URL https://www.hindustantimes.com/india-news/exit-blame-apology-and-centres-warning-galgotias-universitys-chinese-robodog-row-at-ai-summit-2026-key-points-101771466897249.html

,title,href,body,text
0,Galgotias University booted from India AI Impa...,https://apnews.com/article/india-ai-chinese-ga...,A private Indian university has been booted fr...,Add AP News as your preferred source to see mo...
1,"Made in China, unmade at summit: Galgotias exi...",https://indianexpress.com/article/india/galgot...,Greater Noida-based Galgotias University was m...,Greater Noida-based Galgotias University was m...
2,Galgotias University asked to vacate AI Impact...,https://economictimes.indiatimes.com/ai/ai-ins...,Galgotias University faced removal from the AI...,It seems like you're already an ETPrime member...
3,Galgotias University staff leave AI Impact Exp...,https://www.cnbctv18.com/technology/galgotias-...,Galgotias University confirms its Robodog at A...,\n\n#WATCH | Delhi | Galgotias University staf...
4,"Exit, blame, warning: Galgotias' Chinese robod...",https://www.hindustantimes.com/india-news/exit...,Galgotias University found itself in the eye o...,NaN
5,Galgotias University AI Robot Dog Controversy ...,https://www.ndtv.com/india-news/galgotias-univ...,A row has erupted at the India AI Impact Summi...,"Professor Neha Singh, who appeared in the orig..."
6,Galgotias University officials leave AI Impact...,https://www.livemint.com/news/india/galgotias-...,This came after reports suggested that Galgoti...,Galgotiyas University staff and officials were...
7,Galgotias University asked to vacate AI Summit...,https://www.thehindu.com/sci-tech/technology/g...,Organisers of the AI Impact Summit ousted priv...,Organisers of the AI Impact Summit ousted priv...
8,Galgotias University Expelled From India AI Su...,https://www.outlookbusiness.com/news/galgotias...,Galgotias University Expelled From India AI Su...,“The recently acquired Robodog from Unitree is...
9,Galgotias University vacate stall at India AI ...,https://www.wionews.com/world/-it-is-a-legacy-...,Galgotias University staff and officials vacat...,India's Galgotias University courted a major c...

In [14]:
df.to_csv("C:/Users/faman/Downloads/ddgs_results.csv", index=False)

Data preparation

In [15]:
df.dropna(inplace=True)
df

,title,href,body,text
0,Galgotias University booted from India AI Impa...,https://apnews.com/article/india-ai-chinese-ga...,A private Indian university has been booted fr...,Add AP News as your preferred source to see mo...
1,"Made in China, unmade at summit: Galgotias exi...",https://indianexpress.com/article/india/galgot...,Greater Noida-based Galgotias University was m...,Greater Noida-based Galgotias University was m...
2,Galgotias University asked to vacate AI Impact...,https://economictimes.indiatimes.com/ai/ai-ins...,Galgotias University faced removal from the AI...,It seems like you're already an ETPrime member...
3,Galgotias University staff leave AI Impact Exp...,https://www.cnbctv18.com/technology/galgotias-...,Galgotias University confirms its Robodog at A...,\n\n#WATCH | Delhi | Galgotias University staf...
5,Galgotias University AI Robot Dog Controversy ...,https://www.ndtv.com/india-news/galgotias-univ...,A row has erupted at the India AI Impact Summi...,"Professor Neha Singh, who appeared in the orig..."
6,Galgotias University officials leave AI Impact...,https://www.livemint.com/news/india/galgotias-...,This came after reports suggested that Galgoti...,Galgotiyas University staff and officials were...
7,Galgotias University asked to vacate AI Summit...,https://www.thehindu.com/sci-tech/technology/g...,Organisers of the AI Impact Summit ousted priv...,Organisers of the AI Impact Summit ousted priv...
8,Galgotias University Expelled From India AI Su...,https://www.outlookbusiness.com/news/galgotias...,Galgotias University Expelled From India AI Su...,“The recently acquired Robodog from Unitree is...
9,Galgotias University vacate stall at India AI ...,https://www.wionews.com/world/-it-is-a-legacy-...,Galgotias University staff and officials vacat...,India's Galgotias University courted a major c...

need to automate the next cell, don't know how yet

In [17]:
df.drop([0,2],axis=0, inplace=True)
df.reset_index(drop=True, inplace=True)
df

,title,href,body,text
0,"Made in China, unmade at summit: Galgotias exi...",https://indianexpress.com/article/india/galgot...,Greater Noida-based Galgotias University was m...,Greater Noida-based Galgotias University was m...
1,Galgotias University staff leave AI Impact Exp...,https://www.cnbctv18.com/technology/galgotias-...,Galgotias University confirms its Robodog at A...,\n\n#WATCH | Delhi | Galgotias University staf...
2,Galgotias University AI Robot Dog Controversy ...,https://www.ndtv.com/india-news/galgotias-univ...,A row has erupted at the India AI Impact Summi...,"Professor Neha Singh, who appeared in the orig..."
3,Galgotias University officials leave AI Impact...,https://www.livemint.com/news/india/galgotias-...,This came after reports suggested that Galgoti...,Galgotiyas University staff and officials were...
4,Galgotias University asked to vacate AI Summit...,https://www.thehindu.com/sci-tech/technology/g...,Organisers of the AI Impact Summit ousted priv...,Organisers of the AI Impact Summit ousted priv...
5,Galgotias University Expelled From India AI Su...,https://www.outlookbusiness.com/news/galgotias...,Galgotias University Expelled From India AI Su...,“The recently acquired Robodog from Unitree is...
6,Galgotias University vacate stall at India AI ...,https://www.wionews.com/world/-it-is-a-legacy-...,Galgotias University staff and officials vacat...,India's Galgotias University courted a major c...

pre-processing